name: Publish
on:
  - push
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "16"
          - "18"
          - "20"
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm t
      - run: npm run format
      - name: commit auto fixes
        env:
          USERNAME: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "$(git diff --quiet && echo 0 || echo $?)" -gt 0 ]; then
            git config --global user.email "${USERNAME}@users.noreply.github.com" --replace-all
            git config --global user.name "$USERNAME" --replace-all
            git commit -am "😎 Autofix"
            git remote set-url origin https://${TOKEN}@github.com/$REPO.git
            git push origin $BRANCH
            exit 1
          fi
      - name: Publish
        if: github.ref == 'refs/heads/main' && matrix.node-version == '20'
        run: |
          npm run build
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npx @lets/publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
